---

- name: Copy K3s service file
  register: k3s_agent_service
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-agent.service"
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"

- name: Enable and check K3s service
  systemd:
    name: k3s-agent
    daemon_reload: "{{ 'yes' if k3s_agent_service.changed else 'no' }}"
    state:  "{{ 'restarted' if k3s_agent_service.changed else 'started' }}"
    enabled: yes
