all:
  children:
    public_ip:
      hosts:
        helium.dysnomia.studio:
        lithium.dysnomia.studio:
        beryllium.dysnomia.studio:
        bore.dysnomia.studio:

    k3s_server:
      hosts:
        192.168.1.3:
        192.168.1.4:
        192.168.1.5:

    k3s_cluster:
      hosts:
        192.168.1.3:
        192.168.1.4:
        192.168.1.5:
