all:
  children:
    public_ip:
      hosts:
        carbon.dysnomia.studio:
        nitrogen.dysnomia.studio:
        oxygen.dysnomia.studio:

    private_ip:
      hosts:
        192.168.1.6:
        192.168.1.7:
        192.168.1.8:

    ## Groups for playbooks
    k3s_cluster:
      children:
          server:
            children:
              private_ip:
          agent:
            children:
              private_ip:

    postgres_backup_servers:
      children:
        private_ip: