all:
  children:
    public_ip:
      hosts:
        helium.dysnomia.studio:
        lithium.dysnomia.studio:
        beryllium.dysnomia.studio:
        bore.dysnomia.studio:

    private_ip:
      hosts:
        #192.168.1.2
        192.168.1.3:
        192.168.1.4:
        192.168.1.5:

    ## Groups for playbooks
    k3s_server:
      children:
        private_ip:

    k3s_cluster:
      children:
        private_ip:

    postgres_cluster:
      hosts:
        192.168.1.3:

    postgres_backup_servers:
      hosts:
        192.168.1.3:
        192.168.1.4: