---
? ''
: - ttl: 0
    type: A
    values:
    - 188.165.200.10
    - 37.187.74.34
    - 176.9.116.19
  - ttl: 0
    type: AAAA
    values:
    - '2001:41d0:2:910a::1'
    - '2001:41d0:a:2a22::1'
    - '2a01:4f8:151:64ec::'
  - ttl: 0
    type: NS
    values:
    - dns13.ovh.net.
    - ns13.ovh.net.
www:
  ttl: 0
  type: CNAME
  value: achieve.games.
