---
? ''
: - ttl: 0
    type: A
    values:
    - 138.201.58.15
    - 51.75.131.105
  - ttl: 0
    type: AAAA
    values:
    - '2001:41d0:303:8a69::'
    - 2a01:4f8:172:130e::2
  - ttl: 0
    type: NS
    values:
    - dns104.ovh.net.
    - ns104.ovh.net.
  - ttl: 0
    type: TXT
    value: google-site-verification=bZJB43Jv80kaRDEFXQCQ6HmnKcb_5TUuU-ES_46Pa2U
www:
  ttl: 0
  type: CNAME
  value: dehash.me.
