---
? ''
: - ttl: 0
    type: A
    values:
    - 188.165.200.10
    - 37.187.74.34
    - 176.9.116.19
  - ttl: 0
    type: AAAA
    values:
    - '2001:41d0:2:910a::1'
    - '2001:41d0:a:2a22::1'
    - '2a01:4f8:151:64ec::2'
  - ttl: 0
    type: NS
    values:
    - dns104.ovh.net.
    - ns104.ovh.net.
  - ttl: 0
    type: TXT
    value: google-site-verification=bZJB43Jv80kaRDEFXQCQ6HmnKcb_5TUuU-ES_46Pa2U
www:
  ttl: 0
  type: CNAME
  value: dehash.me.
