---
? ''
: - ttl: 0
    type: A
    values:
    - 94.23.197.186
    - 138.201.58.15
    - 51.75.131.105
  - ttl: 0
    type: AAAA
    values:
    - '2001:41d0:2:48ba::'
    - '2001:41d0:303:8a69::'
    - 2a01:4f8:172:130e::2
  - ttl: 0
    type: NS
    values:
    - dns110.ovh.net.
    - ns110.ovh.net.
  - ttl: 0
    type: SPF
    value: v=spf1 include:mx.ovh.com ~all
  - ttl: 0
    type: TXT
    values:
    - 1|www.elanis.fr
    - google-site-verification=E8GgFJkEmJGEHxyaGGQOK0S45yeAIzEKFHxaNVzXY-Y
www:
  ttl: 0
  type: CNAME
  value: elanis.fr.
