---
? ''
: - ttl: 0
    type: A
    values:
    - 188.165.200.10
    - 37.187.74.34
    - 176.9.116.19
  - ttl: 0
    type: AAAA
    values:
    - '2001:41d0:2:910a::1'
    - '2001:41d0:a:2a22::1'
    - '2a01:4f8:151:64ec::'
  - ttl: 0
    type: MX
    values:
    - exchange: mail.protonmail.ch.
      preference: 10
    - exchange: mailsec.protonmail.ch.
      preference: 20
  - ttl: 0
    type: NS
    values:
    - dns110.ovh.net.
    - ns110.ovh.net.
  - ttl: 600
    type: SPF
    value: v=spf1 include:_spf.protonmail.ch mx ~all
  - ttl: 600
    type: TXT
    values:
    - protonmail-verification=85680000d0d9cdc39c2dd1164b0e4efb51790ce6
    - v=spf1 include:_spf.protonmail.ch mx ~all
01.cdn:
  ttl: 0
  type: CNAME
  value: elanis.eu.
_atproto:
  ttl: 0
  type: TXT
  value: did=did:plc:eeelvuw2ecigd2ltjjdor47m
_dmarc:
  ttl: 0
  type: TXT
  value: v=DMARC1\; p=none
protonmail2._domainkey:
  ttl: 0
  type: CNAME
  value: protonmail2.domainkey.dow7ykiver4zlzq2dyohfdqqsp3kuol6ltpyuck4mhfrmrfruyiga.domains.proton.ch.
protonmail3._domainkey:
  ttl: 0
  type: CNAME
  value: protonmail3.domainkey.dow7ykiver4zlzq2dyohfdqqsp3kuol6ltpyuck4mhfrmrfruyiga.domains.proton.ch.
protonmail._domainkey:
  ttl: 0
  type: CNAME
  value: protonmail.domainkey.dow7ykiver4zlzq2dyohfdqqsp3kuol6ltpyuck4mhfrmrfruyiga.domains.proton.ch.
www:
  ttl: 0
  type: CNAME
  value: elanis.eu.
