---
? ''
: - ttl: 0
    type: A
    values:
    - 188.165.200.10
    - 37.187.74.34
    - 176.9.116.19
  - ttl: 0
    type: AAAA
    values:
    - '2001:41d0:2:910a::1'
    - '2001:41d0:a:2a22::1'
    - '2a01:4f8:151:64ec::2'
  - ttl: 0
    type: NS
    values:
    - dns110.ovh.net.
    - ns110.ovh.net.
  - ttl: 0
    type: SPF
    value: v=spf1 include:mx.ovh.com ~all
  - ttl: 0
    type: TXT
    values:
    - 1|www.elanis.fr
    - google-site-verification=E8GgFJkEmJGEHxyaGGQOK0S45yeAIzEKFHxaNVzXY-Y
www:
  ttl: 0
  type: CNAME
  value: elanis.fr.
