---
? ''
: - ttl: 0
    type: A
    values:
    - 138.201.58.15
    - 51.75.131.105
  - ttl: 0
    type: AAAA
    values:
    - '2001:41d0:303:8a69::'
    - 2a01:4f8:172:130e::2
  - ttl: 0
    type: MX
    values:
    - exchange: mail.protonmail.ch.
      preference: 10
    - exchange: mailsec.protonmail.ch.
      preference: 20
  - type: NS
    values:
    - dns12.ovh.net.
    - ns12.ovh.net.
  - ttl: 600
    type: TXT
    values:
    - 1|www.galactae.eu
    - google-site-verification=ndEQd10aj8Fqzze7IPL1KGtKDsil5Ifn5EcDsVZ3WOA
    - protonmail-verification=d05fb1a3ce8f2158bf416f0b99bac2773dfcc91f
    - v=spf1 include:_spf.protonmail.ch mx ~all
'*':
  ttl: 0
  type: CNAME
  value: galactae.eu.
protonmail2._domainkey:
  ttl: 0
  type: CNAME
  value: protonmail2.domainkey.du3tvjslt2bmloqphc7tacc6rp4tnysyrl3jcziichndkn2wbajba.domains.proton.ch.
protonmail3._domainkey:
  ttl: 0
  type: CNAME
  value: protonmail3.domainkey.du3tvjslt2bmloqphc7tacc6rp4tnysyrl3jcziichndkn2wbajba.domains.proton.ch.
protonmail._domainkey:
  ttl: 0
  type: CNAME
  value: protonmail2.domainkey.du3tvjslt2bmloqphc7tacc6rp4tnysyrl3jcziichndkn2wbajba.domains.proton.ch.
www:
  ttl: 0
  type: CNAME
  value: galactae.eu.
