---
- name: Aliases
  hosts: private_ip
  become: true
  become_user: root
  tasks:
    - name: Add argocd-dashboard alias on servers
      lineinfile:
        path=/root/.bashrc
        line="alias argocd-dashboard=\"kubectl port-forward -n argocd svc/argocd-server 8080:443 --address='192.168.1.3'\""
        owner=root
        regexp='^alias traefik-dashboard='
        state=present
        insertafter=EOF
        create=True

    - name: Add grafana-dashboard alias on servers
      lineinfile:
        path=/root/.bashrc
        line="alias grafana-dashboard=\"kubectl port-forward -n kube-system \\"$(kubectl get pods -n kube-system | grep '^grafana-' | awk '{print $1}')\\" 3000:3000 --address='192.168.1.3'\""
        owner=root
        regexp='^alias grafana-dashboard='
        state=present
        insertafter=EOF
        create=True

    - name: Add pgwatch-admin alias on servers
      lineinfile:
        path=/root/.bashrc
        line="alias pgwatch-admin=\"kubectl port-forward -n kube-system \\"$(kubectl get pods -n kube-system | grep '^pgwatch-' | awk '{print $1}')\\" 8081:8080 --address='192.168.1.3'\""
        owner=root
        regexp='^alias pgwatch-admin='
        state=present
        insertafter=EOF
        create=True

    - name: Add traefik-dashboard alias on servers
      lineinfile:
        path=/root/.bashrc
        line="alias traefik-dashboard=\"kubectl port-forward -n kube-system \\"$(kubectl get pods -n kube-system | grep '^traefik-' | awk '{print $1}')\\" 9000:9000 --address='192.168.1.3'\""
        owner=root
        regexp='^alias traefik-dashboard='
        state=present
        insertafter=EOF
        create=True
