---
- name: Aliases
  hosts: private_ip
  become: true
  become_user: root
  tasks:
    - name: Add argocd-dashboard alias on servers
      lineinfile:
        path=/root/.bashrc
        line="alias argocd-dashboard=\"kubectl port-forward -n argocd svc/argocd-server 8080:443 --address='192.168.1.3'\""
        owner=root
        regexp='^alias argocd-dashboard='
        state=present
        insertafter=EOF
        create=True

    - name: Add grafana-dashboard alias on servers
      lineinfile:
        path=/root/.bashrc
        line="alias grafana-dashboard=\"kubectl port-forward -n kube-system \\"$(kubectl get pods -n kube-system | grep '^grafana-' | awk '{print $1}')\\" 3000:3000 --address='192.168.1.3'\""
        owner=root
        regexp='^alias grafana-dashboard='
        state=present
        insertafter=EOF
        create=True

    - name: kubectlgetall command
      lineinfile:
        path=/root/.bashrc
        line="kubectlgetall() { for i in $(kubectl api-resources --verbs=list --namespaced -o name | grep -v \"events.events.k8s.io\" | grep -v \"events\" | sort | uniq); do echo \"Resource:\" $i; kubectl -n ${1} get --ignore-not-found ${i}; done; }"
        owner=root
        regexp='^kubectlgetall() {'
        state=present
        insertafter=EOF
        create=True

    - name: Add longhorn-dashboard alias on servers
      lineinfile:
        path=/root/.bashrc
        line="alias longhorn-dashboard=\"kubectl port-forward -n longhorn-system svc/longhorn-frontend 8082:80 --address='192.168.1.3'\""
        owner=root
        regexp='^alias longhorn-dashboard='
        state=present
        insertafter=EOF
        create=True

    - name: Add pgwatch-admin alias on servers
      lineinfile:
        path=/root/.bashrc
        line="alias pgwatch-admin=\"kubectl port-forward -n kube-system \\"$(kubectl get pods -n kube-system | grep '^pgwatch-' | awk '{print $1}')\\" 8081:8080 --address='192.168.1.3'\""
        owner=root
        regexp='^alias pgwatch-admin='
        state=present
        insertafter=EOF
        create=True

    - name: Add postgres-route alias on servers
      lineinfile:
        path=/root/.bashrc
        line="alias postgres-route=\"kubectl port-forward -n dysnomia-apps svc/postgres 15432:5432 --address='192.168.1.3'\""
        owner=root
        regexp='^alias postgres-route='
        state=present
        insertafter=EOF
        create=True

    - name: Add traefik-dashboard alias on servers
      lineinfile:
        path=/root/.bashrc
        line="alias traefik-dashboard=\"kubectl port-forward -n kube-system \\"$(kubectl get pods -n kube-system | grep '^traefik-' | awk '{print $1}')\\" 9000:9000 --address='192.168.1.3'\""
        owner=root
        regexp='^alias traefik-dashboard='
        state=present
        insertafter=EOF
        create=True
