---
- name: Aliases
  hosts: private_ip
  become: true
  become_user: root
  tasks:
    - name: kubectlgetall command
      lineinfile:
        path=/root/.bashrc
        line="kubectlgetall() { for i in $(kubectl api-resources --verbs=list --namespaced -o name | grep -v \"events.events.k8s.io\" | grep -v \"events\" | sort | uniq); do echo \"Resource:\" $i; kubectl -n ${1} get --ignore-not-found ${i}; done; }"
        owner=root
        regexp='^kubectlgetall() {'
        state=present
        insertafter=EOF
        create=True

    - name: Add kube-oldest-pods alias on servers
      lineinfile:
        path=/root/.bashrc
        line="alias kube-oldest-pods=\"kubectl get pods --all-namespaces --sort-by=.metadata.creationTimestamp | grep -v kube-system | grep -v longhorn-system | head -n 20\""
        owner=root
        regexp='^alias kube-oldest-pods='
        state=present
        insertafter=EOF
        create=True