---
- name: Update argocd
  hosts: private_ip[0]
  become: true
  become_user: root
  tasks:
    - name: Update argocd
      command: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml