- name: Setup firewall rules
  hosts: private_ip
  become: true
  become_user: root
  tasks:
    - name: Iptables flush filter
      iptables:
        chain: "{{ item }}"
        flush: yes
      with_items:  [ 'INPUT', 'FORWARD', 'OUTPUT' ]

    - name: Iptables flush nat
      iptables:
        table: nat
        chain: '{{ item }}'
        flush: yes
      with_items: [ 'INPUT', 'OUTPUT', 'PREROUTING', 'POSTROUTING' ]

    - name: Allow all loopback traffic (INPUT)
      iptables:
        action: append
        chain: INPUT
        in_interface: lo
        jump: ACCEPT

    - name: Allow all loopback traffic (FORWARD)
      iptables:
        action: append
        chain: FORWARD
        in_interface: lo
        jump: ACCEPT

    - name: Allow all wireguard mesh network traffic (INPUT)
      iptables:
        action: append
        chain: INPUT
        in_interface: wg0
        jump: ACCEPT

    - name: Allow all wireguard mesh network traffic (FORWARD)
      iptables:
        action: append
        chain: FORWARD
        in_interface: wg0
        jump: ACCEPT

    - name: Allow related and established connections (INPUT)
      ansible.builtin.iptables:
        chain: INPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT

    - name: Allow related and established connections (OUTPUT)
      ansible.builtin.iptables:
        chain: OUTPUT
        ctstate: ESTABLISHED,RELATED
        jump: ACCEPT

    # Ping
    - name: Allow ping traffic
      iptables:
        chain: INPUT
        jump: ACCEPT
        protocol: icmp

    - name: Allow ping traffic (OUTPUT)
      iptables:
        chain: OUTPUT
        jump: ACCEPT
        protocol: icmp

    # SSH
    - name: Allow port 22/SSH traffic (INPUT)
      iptables:
        chain: INPUT
        destination_port: '22'
        jump: ACCEPT
        protocol: tcp

    - name: Allow port 22/SSH traffic (OUTPUT)
      iptables:
        chain: OUTPUT
        destination_port: '22'
        jump: ACCEPT
        protocol: tcp        

    # FTP (to access to SoYouStart backup servers)
    - name: Allow port 21/FTP traffic (OUTPUT)
      iptables:
        chain: OUTPUT
        destination_port: '21'
        jump: ACCEPT
        protocol: tcp

    - name: Allow port 20/FTP traffic (OUTPUT)
      iptables:
        chain: OUTPUT
        destination_port: '20'
        jump: ACCEPT
        protocol: tcp

    # DNS
    - name: Allow port 53/DNS traffic (OUTPUT)
      iptables:
        chain: OUTPUT
        destination_port: '53'
        jump: ACCEPT
        protocol: udp

    # Web
    - name: Allow port 80/HTTP traffic (FORWARD)
      iptables:
        chain: FORWARD
        destination_port: '80'
        jump: ACCEPT
        protocol: tcp

    - name: Allow port 80/HTTP traffic (INPUT)
      iptables:
        chain: INPUT
        destination_port: '80'
        jump: ACCEPT
        protocol: tcp

    - name: Allow port 80/HTTP traffic (OUTPUT)
      iptables:
        chain: OUTPUT
        destination_port: '80'
        jump: ACCEPT
        protocol: tcp

    - name: Allow port 443/HTTPS traffic (FORWARD)
      iptables:
        chain: FORWARD
        destination_port: '443'
        jump: ACCEPT
        protocol: tcp

    - name: Allow port 443/HTTPS traffic (INPUT)
      iptables:
        chain: INPUT
        destination_port: '443'
        jump: ACCEPT
        protocol: tcp

    - name: Allow port 443/HTTPS traffic (OUTPUT)
      iptables:
        chain: OUTPUT
        destination_port: '443'
        jump: ACCEPT
        protocol: tcp


    # Mail Server
    # Not opening 110 (POP3) / 995 (POP3S) as we don't use it
    - name: Allow port 25/SMTP traffic (INPUT)
      iptables:
        chain: INPUT
        destination_port: '25'
        jump: ACCEPT
        protocol: tcp

    - name: Allow port 25/SMTP traffic (OUTPUT)
      iptables:
        chain: OUTPUT
        destination_port: '25'
        jump: ACCEPT
        protocol: tcp

    - name: Allow port 465/SMTPS traffic (INPUT)
      iptables:
        chain: INPUT
        destination_port: '465'
        jump: ACCEPT
        protocol: tcp

    - name: Allow port 465/SMTPS traffic (OUTPUT)
      iptables:
        chain: OUTPUT
        destination_port: '465'
        jump: ACCEPT
        protocol: tcp

    - name: Allow port 587/SMTP traffic (INPUT)
      iptables:
        chain: INPUT
        destination_port: '587'
        jump: ACCEPT
        protocol: tcp

    - name: Allow port 587/SMTP traffic (OUTPUT)
      iptables:
        chain: OUTPUT
        destination_port: '587'
        jump: ACCEPT
        protocol: tcp

    - name: Allow port 143/IMAP traffic (INPUT)
      iptables:
        chain: INPUT
        destination_port: '143'
        jump: ACCEPT
        protocol: tcp

    - name: Allow port 143/IMAP traffic (OUTPUT)
      iptables:
        chain: OUTPUT
        destination_port: '143'
        jump: ACCEPT
        protocol: tcp

    - name: Allow port 993/IMAPS traffic (INPUT)
      iptables:
        chain: INPUT
        destination_port: '993'
        jump: ACCEPT
        protocol: tcp

    - name: Allow port 993/IMAPS traffic (OUTPUT)
      iptables:
        chain: OUTPUT
        destination_port: '993'
        jump: ACCEPT
        protocol: tcp

    # VPN
    - name: Allow port 1194/VPN traffic (INPUT)
      iptables:
        chain: INPUT
        destination_port: '1194'
        jump: ACCEPT
        protocol: udp

    # NTP
    - name: Allow port 123/NTP traffic (OUTPUT)
      iptables:
        chain: OUTPUT
        destination_port: '123'
        jump: ACCEPT
        protocol: udp

    # Wireguard
    - name: Allow wireguard listener port (51820) (INPUT)
      iptables:
        chain: INPUT
        destination_port: '51820'
        jump: ACCEPT
        protocol: udp 

    - name: Allow wireguard listener port (51820) (OUTPUT)
      iptables:
        chain: OUTPUT
        destination_port: '51820'
        jump: ACCEPT
        protocol: udp

    # K3S
    - name: Allow all traffic on 127.0.0.0/24
      iptables:
        chain: OUTPUT
        destination: 127.0.0.0/24
        jump: ACCEPT

    - name: Allow all traffic on 192.168.1.0/24
      iptables:
        chain: OUTPUT
        destination: 192.168.1.0/24
        jump: ACCEPT

    - name: Allow all traffic on 192.168.50.0/24
      iptables:
        chain: OUTPUT
        destination: 192.168.50.0/24
        jump: ACCEPT

    - name: Allow all traffic on 10.0.0.0/8 (OUTPUT)
      iptables:
        chain: OUTPUT
        destination: 10.0.0.0/8
        jump: ACCEPT

    - name: Allow all traffic on 10.0.0.0/8 (INPUT)
      iptables:
        chain: FORWARD
        destination: 10.0.0.0/8
        jump: ACCEPT

    - name: Allow all traffic on 10.0.0.0/8 (FORWARD)
      iptables:
        chain: FORWARD
        destination: 10.0.0.0/8
        jump: ACCEPT

    # Flannel
    - name: Allow all traffic from helium (94.23.197.186) (INPUT)
      iptables:
        chain: INPUT
        source: 94.23.197.186
        jump: ACCEPT

    - name: Allow all traffic from lithium (138.201.58.15) (INPUT)
      iptables:
        chain: INPUT
        source: 138.201.58.15
        jump: ACCEPT

    - name: Allow all traffic from beryllium (51.75.131.105) (INPUT)
      iptables:
        chain: INPUT
        source: 51.75.131.105
        jump: ACCEPT

    - name: Allow flannel listener port (8472) (OUTPUT)
      iptables:
        chain: OUTPUT
        destination_port: '8472'
        jump: ACCEPT
        protocol: udp

    # Drop other traffic
    - name: Drop any traffic without rule (INPUT)
      iptables:
        chain: INPUT
        jump: DROP

    - name: Drop any traffic without rule (OUTPUT)
      iptables:
        chain: OUTPUT
        jump: DROP