---
- name: Setup kubernetes secrets
  hosts: private_ip[0]
  become: true
  become_user: root
  tasks:
    - name: Creates temp directory
      ansible.builtin.file:
        path: /tmp/kube-secrets
        state: directory

    - name: Copy secrets files
      ansible.builtin.copy:
        src: "kube-secrets/"
        dest: "/tmp/kube-secrets/"
        owner: root
        group: root
        mode: '0644'

    - name: Create secrets
      shell: |
        cd "/tmp/kube-secrets/{{ item }}"
        kubectl apply -k secrets/ -n {{ item }}
      register: create_secrets
      loop:
      - achieve-games
      - alchemistry-leaderboard
      - cours-m1
      - discord-server-stats
      - factory-server-prod
      - factory-server-ptb
      - galactae
      - lumen-server
      - monitoring
      - seafile

    - debug: msg="{{ item.stdout_lines | join("\n") }}"
      with_items: "{{ create_secrets['results'] }}"
    - debug: msg="{{ item.stderr_lines | join("\n") }}"
      with_items: "{{ create_secrets['results'] }}"

    - name: Create argocd notification secrets
      shell: |
        kubectl apply -f /tmp/kube-secrets/argocd/secret.yaml -n argocd
      register: create_argo_secrets

    - debug: msg="{{ create_argo_secrets.stdout_lines | join("\n") }}"
    - debug: msg="{{ create_argo_secrets.stderr_lines | join("\n") }}"

    - name: Delete temp directory
      ansible.builtin.file:
        state: absent
        path: /tmp/kube-secrets/