---
- name: Replicate docker images secrets across namespaces
  hosts: private_ip[0]
  become: true
  become_user: root
  tasks:
    - name: Grant access to Github Packages
      shell: |
        kubectl delete secret github -n {{ item }} || true
        kubectl create secret docker-registry -n {{ item }} github --docker-server=ghcr.io --docker-username={{ argocd_github_username }} --docker-password={{ argocd_github_token }} --docker-email={{ argocd_github_mail }}
      loop:
      - achieve-games
      - alchemistry-leaderboard
      - dehash-me
      - discord-server-stats
      - dysnomia-apps
      - dysnomia-website
      - dysnomia-wiki
      - elanis-cdn
      - factory-server-prod
      - factory-server-ptb
      - galactae
      - gaspar
      - lumen-server
      - monitoring
      - portfolio
      - redmine
      - sonarqube