---
- name: Replicate github secret across namespaces
  hosts: private_ip[0]
  become: true
  become_user: root
  tasks:
    - name: Create secrets
      shell: |
        kubectl get secret github -n dysnomia-apps -o yaml | sed s/"namespace: dysnomia-apps"/"namespace: {{ item }}"/ | kubectl apply -n {{ item }} -f -
      loop:
      - achieve-games
      - alchemistry-leaderboard
      - dehash-me
      - discord-server-stats
      - dysnomia-website
      - dysnomia-wiki
      - elanis-cdn
      - factory-server-prod
      - factory-server-ptb
      - galactae
      - gaspar
      - homepage
      - lumen-server
      - monitoring
      - n8n
      - portfolio
      - redmine
      - seafile
      - sonarqube