---
- name: Check every tool is installed
  hosts: public_ip
  become: true
  become_user: root
  tasks:
  - name: Install linux-headers-generic
    ansible.builtin.package:
      name: linux-headers-generic
      state: present

  - name: Install wireguard
    ansible.builtin.package:
      name: wireguard
      state: present

  - name: Copy configuration
    ansible.builtin.copy:
      src: ../../wireguard/output/{{ inventory_hostname }}.conf 
      dest: /etc/wireguard/wg0.conf
      owner: root
      group: root
      mode: '0644'

  - name: Restart service
    ansible.builtin.service:
      name: wg-quick@wg0
      state: restarted
      enabled: yes

  # TODO: use handler to prevent restarting for no reason