- hosts: private_ip
  gather_facts: yes
  become: false
  tasks:
  - name: System details
    debug: msg="{{ item }}"
    with_items: 
    - "{{ ansible_distribution }}"
    - "{{ ansible_distribution_release }}"
    - "{{ ansible_distribution_version }}"
    - "{{ ansible_distribution_major_version }}"