---
- name: Check every tool is installed
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: Install htop
    ansible.builtin.package:
      name: htop
      state: present

  - name: Install nano
    ansible.builtin.package:
      name: nano
      state: present

  - name: Install tmux
    ansible.builtin.package:
      name: tmux
      state: present