---
- name: Setup Hashicorp vault secrets
  hosts: private_ip[0]
  become: true
  become_user: root
  tasks:
    - name: vault operator unseal
      shell: |
        kubectl exec --stdin=true --tty=true {{ item }} -n vault -- vault operator unseal "{{ hashicorp_vault_keys[0] }}"
        kubectl exec --stdin=true --tty=true {{ item }} -n vault -- vault operator unseal "{{ hashicorp_vault_keys[1] }}"
        kubectl exec --stdin=true --tty=true {{ item }} -n vault -- vault operator unseal "{{ hashicorp_vault_keys[2] }}"
        kubectl exec --stdin=true --tty=true {{ item }} -n vault -- vault operator unseal "{{ hashicorp_vault_keys[3] }}"
      register: vault_unseal
      loop:
        - vault-0
        - vault-1
        - vault-2

    - debug: msg="{{ item.stdout_lines | join("\n") }}"
      with_items: "{{ vault_unseal['results'] }}"
    - debug: msg="{{ item.stderr_lines | join("\n") }}"
      with_items: "{{ vault_unseal['results'] }}"