---
- name: Setup Hashicorp vault secrets
  hosts: private_ip[0]
  become: true
  become_user: root
  tasks:
    - name: vault operator init
      shell: |
        kubectl exec --stdin=true --tty=true vault-0 -n vault -- vault operator init
      register: vault_init

    - debug: msg="{{ vault_init.stdout }}"
    - debug: msg="{{ vault_init.stderr }}"