---
- name: Setup Hashicorp vault secrets
  hosts: private_ip[0]
  become: true
  become_user: root
  tasks:
    - name: Creates temp directory
      ansible.builtin.file:
        path: /tmp/vault-secrets
        state: directory

    - name: Copy certificates
      ansible.builtin.copy:
        src: "../../vault-ca/{{ item }}"
        dest: "/tmp/vault-secrets/{{ item }}"
        owner: root
        group: root
        mode: '0644'
      loop:
        - "rootCA.crt"
        - "rootCA.key"
        - "rootCA.srl"
        - "vault-tls-cert.crt"
        - "vault-tls-cert.csr"
        - "vault-tls-cert.key"

    - name: Create secrets
      shell: |
        kubectl --namespace='vault' delete secret tls-ca || true
        kubectl --namespace='vault' create secret tls tls-ca --cert /tmp/vault-secrets/rootCA.crt --key /tmp/vault-secrets/rootCA.key
        kubectl --namespace='vault' delete secret tls-server || true
        kubectl --namespace='vault' create secret tls tls-server --cert /tmp/vault-secrets/vault-tls-cert.crt --key /tmp/vault-secrets/vault-tls-cert.key

    - name: Delete temp directory
      ansible.builtin.file:
        state: absent
        path: /tmp/vault-secrets