---
- name: Enable cgroup support if not already enabled
  lineinfile:
    path: /boot/boot.txt
    backrefs: yes
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  register: cgroup_support

- name: Regenerate bootloader image
  shell: ./mkscr
  args:
    chdir: /boot
  notify: reboot
  when: cgroup_support.changed
