---
name: Octodns

on:
  push:
    paths:
      - production/octodns/**
      - .github/workflows/octodns.yml

env:
  OVH_APPLICATION_KEY: ${{ secrets.OVH_OCTODNS_APPLICATION_KEY }}
  OVH_APPLICATION_SECRET: ${{ secrets.OVH_OCTODNS_APPLICATION_SECRET }}
  OVH_CONSUMER_KEY: ${{ secrets.OVH_OCTODNS_CONSUMER_KEY }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r production/octodns/requirements.txt
    - name: Validate octodns config
      run: |
        octodns-validate --config-file=./production/octodns/config/config.yaml
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [lint]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r production/octodns/requirements.txt
    - name: Apply octodns config
      run: |
        octodns-sync --config-file=./production/octodns/config/config.yaml --doit